apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-backend  # for ReplicaSet to know which pods to manage
  template:
    metadata:
      labels:
        app: app-backend
    spec:
      containers:
        - name: backend
          resources:
            # requests are taken from 'kubectl top pods -n=dev' and rounded up
            # requests are equal to limits
            limits:
              cpu: 500m
              memory: 200Mi
          env:
            # pod identification
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: WORKER_NAME
              value: $(POD_NAME)
            # db connection
            - name: DATABASE_URL
              value: app-db  # see db.yaml
            - name: DATABASE_USERNAME
              value: root  # TODO: use a different user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-db
                  key: root-password
          image: app-backend:1.0.0
          ports:
            - name: backend
              containerPort: 8000
          startupProbe:
            httpGet:
              path: /info
              port: backend
            failureThreshold: 30
            periodSeconds: 2
          livenessProbe:
            httpGet:
              path: /info
              port: backend
            failureThreshold: 1  # consider dead after first failure
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: app-backend
spec:
  selector:
    app: app-backend
  ports:
    - name: backend
      protocol: TCP
      port: 80
      targetPort: backend  # see exposed port in container
