apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-backend
  minReplicas: 2
  maxReplicas: 10
  # behavior: - keep the default policies
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
