apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-backend  # for ReplicaSet to know which pods to manage
  template:
    metadata:
      labels:
        app: app-backend
    spec:
      containers:
        - name: backend
          resources:
            # requests are taken from 'kubectl top pods -n=dev' and rounded up
            # requests are equal to limits
            limits:
              cpu: 500m
              memory: 200Mi
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            # - name: COMMENT
            #   valueFrom:
            #     configMapKeyRef:
            #       name: app-config
            #       key: purpose
            - name: WORKER_NAME
              value: $(POD_NAME)  # - $(COMMENT)
          image: app-backend:1.0.0
          ports:
            - name: backend
              containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: app-backend
spec:
  #type: LoadBalancer  # temporary, to test HPA
  selector:
    app: app-backend
  ports:
    - name: backend
      protocol: TCP
      port: 8000
      targetPort: backend  # see exposed port in container
