apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-frontend
  labels:
    release: prometheus-stack  # matches kube-prometheus-stack release label
spec:
  selector:
    matchLabels:
      app: app-frontend
  namespaceSelector:
    matchNames:
      - dev
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
