{
 "title": "Backend overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total amount of requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(flask_http_request_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests per endpoint",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flask_http_request_by_path_total{path=\"/\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(flask_http_request_by_path_total{path=\"/info\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(flask_http_request_by_path_total{path=\"/posts\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "root",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flask_http_request_by_path_total{path=\"/\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "info",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flask_http_request_by_path_total{path=\"/info\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "posts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flask_http_request_by_path_total{path=\"/posts\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}