apiVersion: v1
kind: Service
metadata:
  name: service-app-py
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: app-py
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8000
