apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.appName }}-backend  # for ReplicaSet to know which pods to manage
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-backend
    spec:
      containers:
        - name: backend
          # TODO: how to measure required resources?
          # resources:
          #   requests:
          #     cpu: "0.5"        # https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/
          #     memory: "100Mi"   # https://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource/
          #   limits:
          #     cpu: "1"          # https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/
          #     memory: "200Mi"   # https://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource/
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: COMMENT
              valueFrom:
                configMapKeyRef:
                  key: purpose
                  name: {{ .Values.appName }}-config
            - name: WORKER_NAME
              value: $(POD_NAME) - $(COMMENT)
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          ports:
            - name: backend
              containerPort: 8000
