apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.appName }}-backend  # for ReplicaSet to know which pods to manage
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-backend
    spec:
      containers:
        - name: backend
          resources:
            # requests are taken from 'kubectl top pods -n=dev' and rounded up
            # requests are equal to limits
            limits:
              cpu: 500m
              memory: 200Mi
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: COMMENT
              valueFrom:
                configMapKeyRef:
                  key: purpose
                  name: {{ .Values.appName }}-config
            - name: WORKER_NAME
              value: $(POD_NAME) - $(COMMENT)
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          ports:
            - name: backend
              containerPort: 8000
