apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-backend
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer  # temporary, to test HPA
  selector:
    app: {{ .Values.appName }}-backend
  ports:
    - name: backend
      protocol: TCP
      port: 8000
      targetPort: backend  # see exposed port in container
