apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-frontend
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.appName }}-frontend
  ports:
    - name: frontend
      protocol: TCP
      port: 80
      targetPort: frontend  # see exposed port in container
