apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:  # base64-encoded
  username: c2VjcmV0LXVzZXI=
  password: c2VjcmV0LXBhc3M=
