services:
  backend-db:
    build: db
    develop:
      watch:
        - action: rebuild
          path: db
    environment:
      MYSQL_ROOT_PASSWORD: root-password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s
  backend:
    build: backend
    develop:
      watch:
        - action: rebuild
          path: backend/board
    depends_on:
      backend-db:
        condition: service_healthy
        restart: true
    environment:
      WORKER_NAME: compose_dev
      DATABASE_URL: backend-db
      DATABASE_USERNAME: root  # TODO: use a different user
      DATABASE_PASSWORD: root-password
    ports:
      - "8001:8000"  # expose port to host
  frontend:
    build: frontend-vue
    develop:
      watch:
        - action: rebuild
          path: frontend-vue
    ports:
      - "8002:8000"  # expose port to host
  nginx-reverse-proxy:
    # Routes traffic to backend and frontend based on the request path
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx-rev-proxy.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
  backend-load:
    image: busybox
    depends_on:
      - backend
    command:
      - sh
      - -c
      - while true; do wget -q -O- http://backend:8000/info; sleep 5; done
  frontend-load:
    image: busybox
    depends_on:
      - frontend
    command:
      - sh
      - -c
      - while true; do  wget -Sq -O- http://frontend:8000/ 2>&1 | grep HTTP; sleep 5; done
