kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-messages
nodes:
  - role: control-plane
    # To allow NGINX Ingress controller to work,
    # see: https://kind.sigs.k8s.io/docs/user/ingress/#option-2-extraportmapping
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
  - role: worker
  - role: worker
