"""Flask config"""

import os

DEFAULT_WORKER_NAME = "Unknown worker"

WORKER_NAME = os.getenv("WORKER_NAME", DEFAULT_WORKER_NAME)

DATABASE_URL = os.getenv("DATABASE_URL")
DATABASE_PORT = os.getenv("DATABASE_PORT", "3306")
DATABASE_NAME = os.getenv("DATABASE_NAME", "msgs")
DATABASE_USERNAME = os.getenv("DATABASE_USERNAME")
DATABASE_PASSWORD = os.getenv("DATABASE_PASSWORD")
