apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app-flask
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-flask  # for ReplicaSet to know which pods to manage
  template:
    metadata:
      labels:
        app: app-flask
    spec:
      containers:
        - name: backend
          # TODO: how to measure required resources?
          # resources:
          #   requests:
          #     cpu: "0.5"        # https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/
          #     memory: "100Mi"   # https://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource/
          #   limits:
          #     cpu: "1"          # https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/
          #     memory: "200Mi"   # https://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource/
          env:
            - name: SERVICE_PORT
              value: '8005'
            - name: WORKER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          image: app-flask-py:1.0.0  # don't use 'latest' as it wants to go to DockerHub for the latest
          ports:
            - name: backend
              containerPort: 8005
        - name: frontend
          env:
            - name: SERVICE_PORT
              value: '8000'
            - name: BACKEND_ENDPOINT
              value: http://localhost:8005/backend/time
          image: app-flask-py:1.0.0
          ports:
            - name: frontend
              containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: service-app-flask
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: app-flask
  ports:
    - name: frontend
      protocol: TCP
      port: 80
      targetPort: frontend  # see exposed port in container
    - name: backend
      protocol: TCP
      port: 8005
      targetPort: backend  # see exposed port in container
