apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app-py
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-py  # for ReplicaSet to know which pods to manage
  template:
    metadata:
      labels:
        app: app-py
    spec:
      containers:
        - name: app
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          image: app-py:1.0.0  # don't use 'latest' as it wants to go to DockerHub for the latest
          args: ["--message", "Hello from \"$(MY_POD_NAME)\""]
          ports:
            - containerPort: 8000
