apiVersion: v1
kind: Service
metadata:
  name: test-app-service
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: andrey
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8000
