name: Build and test frontend

on:
  workflow_call:

jobs:
  js-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"  # same as in docker image
      - name: Install dependencies
        run: |
          npm install
        working-directory: app/frontend-vue
      - name: Build
        run: |
          npm run build
        working-directory: app/frontend-vue
      - name: Lint
        run: |
          npm run lint
        working-directory: app/frontend-vue

  docker-frontend:
    runs-on: ubuntu-latest
    needs:
      - js-checks  # no point in testing the image if the functionality is broken
    env:
      IMAGE_TAG: "app-frontend:ci"
      CONTAINER_NAME: frontend
    steps:
      - uses: actions/checkout@v4
      - name: Build the image
        run: |
          docker build -t ${{ env.IMAGE_TAG }} .
        working-directory: app/frontend-vue
      - name: Run the image (in detach mode)
        id: run-image
        run: >
          docker run --rm --detach -p 8000:8000/tcp
          --name ${{ env.CONTAINER_NAME }}
          ${{ env.IMAGE_TAG }}
      - name: Check endpoints
        # TODO: switch to bruno CLI
        run: |
          HTTP_CODE=$(wget -Sq -O- http://localhost:8000/ 2>&1 | grep HTTP)
          echo $HTTP_CODE
          echo $HTTP_CODE | grep "200 OK"
      - name: Stop the container
        if: always() && steps.run-image.outcome == 'success'
        run: |
          docker stop ${{ env.CONTAINER_NAME }}
