name: PR

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install pre-commit
        run: |
          pip install pre-commit
          pre-commit install --install-hooks
      - name: Run pre-commit for all files
        run: |
          pre-commit run --all-files

  pytest-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: >
          python -m pip install
          -r app/backend/requirements.txt
          -r app/backend/requirements-dev.txt
      - name: pytest
        env:
          PROMETHEUS_MULTIPROC_DIR: tmp  # no heading slash
        run: pytest -v
        working-directory: app/backend
