name: PR

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install pre-commit
        run: |
          pip install pre-commit
          pre-commit install --install-hooks
      - name: Run pre-commit for all files
        run: |
          pre-commit run --all-files

  check-backend:
    uses: ./.github/workflows/backend.yaml

  check-frontend:
    uses: ./.github/workflows/frontend.yaml

  conclusion:
    name: Conclusion
    needs:
      # list all verification jobs here
      - pre-commit
      - check-backend
      - check-frontend
    if: always()
    runs-on: ubuntu-latest
    env:
      HAS_FAILURE: ${{ contains(needs.*.outcome, 'failure') }}
    steps:
      - name: Report failure
        if: env.HAS_FAILURE == 'true'
        run: |
          echo "Some jobs failed"
          exit 1
      - name: Report success
        run: echo "no failures"
